[2025-04-17T17:01:09.850+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-04-17T17:01:09.981+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather_api_to_snowflake.load_weather_raw_to_snowflake scheduled__2025-04-17T16:58:00+00:00 [queued]>
[2025-04-17T17:01:10.057+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather_api_to_snowflake.load_weather_raw_to_snowflake scheduled__2025-04-17T16:58:00+00:00 [queued]>
[2025-04-17T17:01:10.066+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2025-04-17T17:01:10.141+0000] {taskinstance.py:2889} INFO - Executing <Task(SnowflakeOperator): load_weather_raw_to_snowflake> on 2025-04-17 16:58:00+00:00
[2025-04-17T17:01:10.181+0000] {standard_task_runner.py:72} INFO - Started process 3367 to run task
[2025-04-17T17:01:10.190+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'weather_api_to_snowflake', 'load_weather_raw_to_snowflake', 'scheduled__2025-04-17T16:58:00+00:00', '--job-id', '70', '--raw', '--subdir', 'DAGS_FOLDER/dbt_snowflake_pipeline.py', '--cfg-path', '/tmp/tmpjo0fd3gi']
[2025-04-17T17:01:10.225+0000] {standard_task_runner.py:105} INFO - Job 70: Subtask load_weather_raw_to_snowflake
[2025-04-17T17:01:10.360+0000] {task_command.py:467} INFO - Running <TaskInstance: weather_api_to_snowflake.load_weather_raw_to_snowflake scheduled__2025-04-17T16:58:00+00:00 [running]> on host b322df8cb9fb
[2025-04-17T17:01:10.976+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='weather_api_to_snowflake' AIRFLOW_CTX_TASK_ID='load_weather_raw_to_snowflake' AIRFLOW_CTX_EXECUTION_DATE='2025-04-17T16:58:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-04-17T16:58:00+00:00'
[2025-04-17T17:01:11.010+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-04-17T17:01:11.096+0000] {sql.py:278} INFO - Executing: 
            CREATE TABLE IF NOT EXISTS STAGING.WEATHER_RAW (
                city STRING,
                timestamp TIMESTAMP,
                temperature FLOAT,
                humidity FLOAT,
                pressure FLOAT,
                description STRING
            );
            INSERT INTO STAGING.WEATHER_RAW (
                city, timestamp, temperature, humidity, pressure, description
            )
            VALUES (
                'Paris',
                CURRENT_TIMESTAMP,
                15.66,
                44,
                1012,
                'clear sky'
            );
        
[2025-04-17T17:01:11.131+0000] {base.py:84} INFO - Retrieving connection 'snowflake_conn'
[2025-04-17T17:01:11.182+0000] {base.py:84} INFO - Retrieving connection 'snowflake_conn'
[2025-04-17T17:01:11.225+0000] {connection.py:423} INFO - Snowflake Connector for Python Version: 3.14.0, Python Version: 3.11.11, Platform: Linux-5.10.76-linuxkit-x86_64-with-glibc2.36
[2025-04-17T17:01:11.241+0000] {connection.py:1226} INFO - Connecting to GLOBAL Snowflake domain
[2025-04-17T17:01:11.245+0000] {connection.py:1315} INFO - This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity.
[2025-04-17T17:01:12.740+0000] {sql.py:553} INFO - Running statement: CREATE TABLE IF NOT EXISTS STAGING.WEATHER_RAW (
                city STRING,
                timestamp TIMESTAMP,
                temperature FLOAT,
                humidity FLOAT,
                pressure FLOAT,
                description STRING
            );, parameters: None
[2025-04-17T17:01:12.956+0000] {sql.py:562} INFO - Rows affected: 1
[2025-04-17T17:01:12.972+0000] {snowflake.py:447} INFO - Rows affected: 1
[2025-04-17T17:01:12.989+0000] {snowflake.py:448} INFO - Snowflake query id: 01bbc0dd-0001-532c-0000-00012aeefc31
[2025-04-17T17:01:13.006+0000] {sql.py:553} INFO - Running statement: INSERT INTO STAGING.WEATHER_RAW (
                city, timestamp, temperature, humidity, pressure, description
            )
            VALUES (
                'Paris',
                CURRENT_TIMESTAMP,
                15.66,
                44,
                1012,
                'clear sky'
            );, parameters: None
[2025-04-17T17:01:13.521+0000] {sql.py:562} INFO - Rows affected: 1
[2025-04-17T17:01:13.538+0000] {snowflake.py:447} INFO - Rows affected: 1
[2025-04-17T17:01:13.545+0000] {snowflake.py:448} INFO - Snowflake query id: 01bbc0dd-0001-532f-0001-2aee000121d6
[2025-04-17T17:01:14.210+0000] {connection.py:810} INFO - closed
[2025-04-17T17:01:15.348+0000] {connection.py:816} INFO - No async queries seem to be running, deleting session
[2025-04-17T17:01:15.645+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-04-17T17:01:15.655+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=weather_api_to_snowflake, task_id=load_weather_raw_to_snowflake, run_id=scheduled__2025-04-17T16:58:00+00:00, execution_date=20250417T165800, start_date=20250417T170110, end_date=20250417T170115
[2025-04-17T17:01:15.790+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-04-17T17:01:15.847+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-04-17T17:01:15.901+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
