[2025-02-11T23:32:37.581+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-11T23:32:37.640+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather_dag.load_data_to_s3 scheduled__2025-02-10T00:00:00+00:00 [queued]>
[2025-02-11T23:32:37.666+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather_dag.load_data_to_s3 scheduled__2025-02-10T00:00:00+00:00 [queued]>
[2025-02-11T23:32:37.668+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-02-11T23:32:37.695+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): load_data_to_s3> on 2025-02-10 00:00:00+00:00
[2025-02-11T23:32:37.717+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=1698) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-02-11T23:32:37.722+0000] {standard_task_runner.py:72} INFO - Started process 1700 to run task
[2025-02-11T23:32:37.731+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'weather_dag', 'load_data_to_s3', 'scheduled__2025-02-10T00:00:00+00:00', '--job-id', '93', '--raw', '--subdir', 'DAGS_FOLDER/weather_dag.py', '--cfg-path', '/tmp/tmpn72i9am7']
[2025-02-11T23:32:37.739+0000] {standard_task_runner.py:105} INFO - Job 93: Subtask load_data_to_s3
[2025-02-11T23:32:37.835+0000] {task_command.py:467} INFO - Running <TaskInstance: weather_dag.load_data_to_s3 scheduled__2025-02-10T00:00:00+00:00 [running]> on host dbef5e540f20
[2025-02-11T23:32:37.996+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='aida' AIRFLOW_CTX_DAG_ID='weather_dag' AIRFLOW_CTX_TASK_ID='load_data_to_s3' AIRFLOW_CTX_EXECUTION_DATE='2025-02-10T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-02-10T00:00:00+00:00'
[2025-02-11T23:32:38.000+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-02-11T23:32:38.035+0000] {logging_mixin.py:190} INFO - Bucket name: weather-data-bucket
[2025-02-11T23:32:38.197+0000] {logging_mixin.py:190} INFO - File uploaded successfully to MinIO!
[2025-02-11T23:32:38.200+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-02-11T23:32:38.236+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-02-11T23:32:38.238+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=weather_dag, task_id=load_data_to_s3, run_id=scheduled__2025-02-10T00:00:00+00:00, execution_date=20250210T000000, start_date=20250211T233237, end_date=20250211T233238
[2025-02-11T23:32:38.319+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-02-11T23:32:38.358+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-02-11T23:32:38.363+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
